export enum ErrorCode {
  // Authentication

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  FORBIDDEN = 'FORBIDDEN',

  // User

  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',

  // Validation

  VALIDATION_ERROR = 'VALIDATION_ERROR',


  // Cart

  CART_NOT_FOUND = 'CART_NOT_FOUND',
  CART_EMPTY = 'CART_EMPTY',
  ACTIVE_CART_NOT_FOUND = 'ACTIVE_CART_NOT_FOUND',
  PRODUCT_NOT_IN_CART = 'PRODUCT_NOT_IN_CART',
  INVALID_CART_QUANTITY = 'INVALID_CART_QUANTITY',
  NO_ACTIVE_CART = 'NO_ACTIVE_CART',


  // Categories

  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_HAS_ASSOCIATED_PRODUCTS = 'CATEGORY_HAS_ASSOCIATED_PRODUCTS',

  // Products

  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  NEGATIVE_STOCK = 'NEGATIVE_STOCK',
  PRODUCT_IN_ACTIVE_ORDER = 'PRODUCT_IN_ACTIVE_ORDER',


  // Orders

  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_EXISTS = 'ORDER_ALREADY_EXISTS',
  EMPTY_CART_ORDER = 'EMPTY_CART_ORDER',
  ORDER_CANCELLATION_NOT_ALLOWED = 'ORDER_CANCELLATION_NOT_ALLOWED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  ORDER_CREATION_FAILED = 'ORDER_CREATION_FAILED',
  

  // Payments

  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_COMPLETED = 'PAYMENT_ALREADY_COMPLETED',
  PAYMENT_ALREADY_SUCCEEDED = 'PAYMENT_ALREADY_SUCCEEDED',
  PAYMENT_NOT_SUCCEEDED = 'PAYMENT_NOT_SUCCEEDED',
  PAYMENT_INTENT_MISMATCH = 'PAYMENT_INTENT_MISMATCH',
  INVALID_PAYMENT_STATE = 'INVALID_PAYMENT_STATE',
  INVALID_PAYMENT_AMOUNT = 'INVALID_PAYMENT_AMOUNT',
  PAYMENT_GATEWAY_ERROR = 'PAYMENT_GATEWAY_ERROR',

  // Database

  UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // System

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}